spring.application.name=taskhub-backend

spring.datasource.url=jdbc:postgresql://taskhub-db.postgres.database.azure.com:5432/TaskHub?sslmode=require
spring.datasource.username=TaskHubAdmin
spring.datasource.password=Azertyuiop$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Hibernate logs
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.root=WARN

# HikariCP (JDBC connection pool)
logging.level.com.zaxxer.hikari=ERROR

logging.level.com.taskhub.taskhub_backend.security=INFO

# Optional debug (uncomment if needed)
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.com.zaxxer.hikari=DEBUG
#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

# Mail configuration
spring.mail.host=smtp.zoho.com
spring.mail.port=465
spring.mail.username=contact@task-hub.tech
spring.mail.password=Ima325+Hb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.properties.mail.debug=false

# JWT configuration
jwt.secret=GfE9ioCi+jXs1tZiX9eVPT9L/9iFy3a1DerNkENn9zuz1G+StvIHzku45HoRss31H3V23UZU7PVfZHWG5mV+/w==
jwt.expirationMs=86400000

# Path matching strategy (important pour Spring 6+)
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# CORS ? à gérer dans un bean Spring Security ou WebMvcConfigurer (pas ici dans properties)
# Ne pas mettre "Access-Control-Allow-Origin" dans application.properties

# Springdoc OpenAPI (Swagger) configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

# Ressources statiques
spring.web.resources.add-mappings=true

# Port serveur (dev local)
server.port=8081
