spring.application.name=taskhub-backend

spring.datasource.url=jdbc:postgresql://taskhub-db.postgres.database.azure.com:5432/TaskHub?sslmode=require
spring.datasource.username=TaskHubAdmin
spring.datasource.password=Azertyuiop$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Optional debug
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

# JWT
jwt.secret=TWFDbMOpcFVsdHJhU2VjcsOpdGUxMjM0NTY3ODkw
jwt.expirationMs=86400000


server.port=8081
